version : "3"

services :
  db_dev:
    container_name: postgres_dev_container
    image: postgres
    environment:
      POSTGRES_USER: "ada-team"
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: "ada"
      PGDATA: /data/postgres
    ports:
      - "15432:5432"
    volumes:
      - pgvol_dev:/data/postgresql
    networks:
      - ada-db-network
    restart: unless-stopped

  db_test:
    container_name: postgres_test_container
    image: postgres
    environment:
      POSTGRES_USER: "ada-team"
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: "ada"
      PGDATA: /data/postgres
    ports:
      - "25432:5432"
    volumes:
      - pgvol_test:/data/postgresql
    networks:
      - ada-db-network
    restart: unless-stopped

  pgadmin :
    container_name: pgadmin_container
    image : dpage/pgadmin4
    environment :
      PGADMIN_DEFAULT_EMAIL : "ada-team@gmail.com"
      PGADMIN_DEFAULT_PASSWORD : "ada-team"
    volumes:
      - pgadminvol:/root/.pgadmin
    ports :
      - "15050:80"
    networks :
      - ada-db-network
    restart: unless-stopped

networks :
  ada-db-network :
    driver : bridge

volumes:
  pgvol_dev:
  pgvol_test:
  pgadminvol: